/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import AccesoADatos.*; //Importa clases para conectarse y ejectuar consultas SQL
import Entidades.*; //Enlaza con las clases de los objetos
import com.sun.glass.events.KeyEvent;
import java.awt.Color; //Para generar color de fondo
import java.awt.Cursor;
import javax.swing.JOptionPane;
import java.util.Objects;

/**
 *
 * @author Carlos
 */
public class formMateria extends javax.swing.JInternalFrame {

    /**
     * Formulario para verificar Materias. Buscar activas, eliminarlas y crear
     * nuevas.
     */
    public formMateria() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana
        botonEliminar.setEnabled(false); //Inhabilita Botón de guardar
        botonGuardar.setEnabled(false); //Inhabilita Botón de eliminar
        campoAnio.setFocusable(false);
        campoAnio.setCursor(null);
        campoNombre.setFocusable(false);
        campoNombre.setCursor(null);
        nuevoNombre.setVisible(false);
        nuevoAnio.setVisible(false);

    }

    public void habilitarEliminar() {
        //Esta sentencia habilita e inhabilita el boton de eliminar
        if (!campoCodigo.getText().isEmpty() && !campoAnio.getText().isEmpty() && !campoNombre.getText().isEmpty()) {
            botonEliminar.setEnabled(true);
        } else {
            botonEliminar.setEnabled(false);
        }
    }

    public void habilitarGuardar() {
        //Esta sentencia habilita e inhabilita el boton de guardar
        if (botonEstado.isSelected() && !campoAnio.getText().isEmpty() && !campoNombre.getText().isEmpty()) {
            botonGuardar.setEnabled(true);
        } else {
            botonGuardar.setEnabled(false);
            botonEstado.setSelected(false);
        }
    }

    public void limpiarPantalla() {
        botonEliminar.setEnabled(false); //Inhabilita Botón de guardar
        botonGuardar.setEnabled(false); //Inhabilita Botón de eliminar
        botonEstado.setSelected(false);
        campoAnio.setText("");
        campoAnio.setFocusable(false);
        campoAnio.setCursor(null);
        campoNombre.setText("");
        campoNombre.setFocusable(false);
        campoNombre.setCursor(null);
        campoCodigo.setText("");
        campoCodigo.setFocusable(true);
        campoCodigo.setEnabled(true);
        campoCodigo.setCursor(Cursor.getPredefinedCursor(2));
        nuevoNombre.setVisible(false);
        nuevoAnio.setVisible(false);
        labelEstado.setText("Activa/Desactivada");
        labelEstado.setForeground(Color.black);
                
    }

    //Instancio objeto Materia y MateriaData para usar en los métodos del formulario
    MateriaData mat = new MateriaData();
    Materia materia = new Materia();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTitle = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoAnio = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        botonEstado = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        botonNuevo = new javax.swing.JToggleButton();
        botonEliminar = new javax.swing.JToggleButton();
        botonGuardar = new javax.swing.JToggleButton();
        botonSalir = new javax.swing.JToggleButton();
        labelEstado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        limpiarPantalla = new javax.swing.JButton();
        nuevoAnio = new javax.swing.JLabel();
        nuevoNombre = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);
        setBorder(null);
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setVisible(true);
        getContentPane().setLayout(null);

        nameTitle.setAlignment(java.awt.Label.CENTER);
        nameTitle.setBackground(java.awt.SystemColor.activeCaption);
        nameTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nameTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nameTitle.setText("Materia");
        getContentPane().add(nameTitle);
        nameTitle.setBounds(358, 10, 68, 26);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Código:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(166, 129, 54, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(166, 189, 59, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Año:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(166, 252, 31, 17);

        campoCodigo.setBackground(new java.awt.Color(255, 255, 255));
        campoCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoCodigo.setForeground(new java.awt.Color(0, 0, 0));
        campoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(campoCodigo);
        campoCodigo.setBounds(264, 129, 144, 23);

        campoNombre.setBackground(java.awt.Color.white);
        campoNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoNombre.setForeground(java.awt.Color.black);
        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNombreKeyReleased(evt);
            }
        });
        getContentPane().add(campoNombre);
        campoNombre.setBounds(264, 189, 144, 23);

        campoAnio.setBackground(java.awt.Color.white);
        campoAnio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoAnio.setForeground(java.awt.Color.black);
        campoAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoAnioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoAnioKeyTyped(evt);
            }
        });
        getContentPane().add(campoAnio);
        campoAnio.setBounds(264, 252, 64, 23);

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscar);
        botonBuscar.setBounds(511, 124, 80, 32);

        botonEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(botonEstado);
        botonEstado.setBounds(264, 332, 28, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estado:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(166, 337, 52, 17);

        botonNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(botonNuevo);
        botonNuevo.setBounds(166, 514, 80, 31);

        botonEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar);
        botonEliminar.setBounds(264, 514, 90, 31);

        botonGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar);
        botonGuardar.setBounds(376, 514, 90, 31);

        botonSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir);
        botonSalir.setBounds(485, 514, 70, 31);

        labelEstado.setForeground(new java.awt.Color(0, 0, 0));
        labelEstado.setText("Activa/Desactivada");
        getContentPane().add(labelEstado);
        labelEstado.setBounds(264, 366, 130, 16);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 0);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(167, 40, 456, 10);

        limpiarPantalla.setText("Limpiar");
        limpiarPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarPantallaActionPerformed(evt);
            }
        });
        getContentPane().add(limpiarPantalla);
        limpiarPantalla.setBounds(510, 170, 80, 32);

        nuevoAnio.setBackground(java.awt.SystemColor.activeCaption);
        nuevoAnio.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        nuevoAnio.setForeground(new java.awt.Color(153, 0, 0));
        nuevoAnio.setText("* Ingrese el año de cursado");
        nuevoAnio.setFocusable(false);
        getContentPane().add(nuevoAnio);
        nuevoAnio.setBounds(270, 280, 210, 13);

        nuevoNombre.setBackground(java.awt.SystemColor.activeCaption);
        nuevoNombre.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        nuevoNombre.setForeground(new java.awt.Color(153, 0, 0));
        nuevoNombre.setText("* Ingrese el nombre de la nueva Materia");
        nuevoNombre.setFocusable(false);
        getContentPane().add(nuevoNombre);
        nuevoNombre.setBounds(270, 210, 210, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();//Cierra ventana de formulario para volver al menú principal

    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        try {
            int codigo = Integer.parseInt(campoCodigo.getText());
            //Convierte el código en int
            materia = mat.buscarMateria(codigo);//genera la busqueda de la materia
            if (!materia.getEstado().equals(null)) {
                //Rellena los campos con la información que llegó de buscarMateria
                try {
                    campoNombre.setText(materia.getNombre());
                    campoAnio.setText(String.valueOf(materia.getAnioMateria()));
                    botonEstado.setSelected(materia.getEstado());
                } catch (NullPointerException ex) {
                    limpiarPantalla();

                }

                // Cambia leyenda debajo del boton de activa e inactiva
                if (botonEstado.isSelected()) {
                    labelEstado.setText("Activa");
                    labelEstado.setForeground(Color.GREEN);
                } else {
                    labelEstado.setText("Desactivada");
                    labelEstado.setForeground(Color.red);
                }

                //Habilita boton de guardar si están todos los campos completos
                if (!campoCodigo.getText().isEmpty() && !campoAnio.getText().isEmpty() && !campoNombre.getText().isEmpty()) {
                    botonGuardar.setEnabled(true);
                    botonEliminar.setEnabled(true);
                }

                //Habilita campos para edición.
                campoAnio.setFocusable(true);
                campoAnio.setCursor(Cursor.getPredefinedCursor(2));
                campoNombre.setFocusable(true);
                campoNombre.setCursor(Cursor.getPredefinedCursor(2));
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese un código para buscar");
            limpiarPantalla();
        }catch (NullPointerException ex){
            limpiarPantalla();
        }


    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        mat.eliminarMateria(Integer.parseInt(campoCodigo.getText()));//Convierte codigo en int para eliminar la materia
        limpiarPantalla();
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void campoCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCodigoKeyReleased
        //Habilita el boton eliminar una vez estén los campos correspondientes completos
        habilitarEliminar();
    }//GEN-LAST:event_campoCodigoKeyReleased

    private void campoNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyReleased
        //Habilita el boton eliminar una vez estén los campos correspondientes completos
        habilitarEliminar();
        habilitarGuardar();
    }//GEN-LAST:event_campoNombreKeyReleased

    private void campoAnioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAnioKeyReleased
        //Habilita el boton eliminar una vez estén los campos correspondientes completos
        habilitarEliminar();
        habilitarGuardar();
    }//GEN-LAST:event_campoAnioKeyReleased

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        //Convierte el código en int para realizar la consulta sql para guardar las modificaciones de la materia
        Materia guardarMateria = new Materia();
        if (!campoCodigo.getText().isEmpty()) {
            guardarMateria.setIdMateria(Integer.parseInt(campoCodigo.getText()));
            guardarMateria.setNombre(campoNombre.getText());
            guardarMateria.setAnioMateria(Integer.parseInt(campoAnio.getText()));
            guardarMateria.setEstado(botonEstado.isSelected());
            mat.modificarMateria(guardarMateria);
        } else {
            guardarMateria.setNombre(campoNombre.getText());
            guardarMateria.setAnioMateria(Integer.parseInt(campoAnio.getText()));
            guardarMateria.setEstado(botonEstado.isSelected());
            mat.guardarMateria(guardarMateria);
        }
        limpiarPantalla();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstadoActionPerformed
        //Habilita el boton guardar una vez estén los campos correspondientes completos
        habilitarGuardar();
    }//GEN-LAST:event_botonEstadoActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        //Convierte el código en int para realizar la consulta sql para guardar la materia nueva
        campoAnio.setFocusable(true);
        campoAnio.setCursor(Cursor.getPredefinedCursor(2));
        campoNombre.setFocusable(true);
        campoNombre.setCursor(Cursor.getPredefinedCursor(2));
        nuevoNombre.setVisible(true);
        nuevoAnio.setVisible(true);
        //campoCodigo.setFocusable(true);
        //campoCodigo.setCursor(null);
        campoCodigo.setText("");
        campoCodigo.setEnabled(false);
        habilitarGuardar();
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void limpiarPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarPantallaActionPerformed
        limpiarPantalla();
    }//GEN-LAST:event_limpiarPantallaActionPerformed

    private void campoCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCodigoKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_campoCodigoKeyTyped

    private void campoAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAnioKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_campoAnioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JToggleButton botonEliminar;
    private javax.swing.JRadioButton botonEstado;
    private javax.swing.JToggleButton botonGuardar;
    private javax.swing.JToggleButton botonNuevo;
    private javax.swing.JToggleButton botonSalir;
    private javax.swing.JTextField campoAnio;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JButton limpiarPantalla;
    private java.awt.Label nameTitle;
    private javax.swing.JLabel nuevoAnio;
    private javax.swing.JLabel nuevoNombre;
    // End of variables declaration//GEN-END:variables
}
