/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import AccesoADatos.*; //AlumnoData;

import Entidades.*; //Alumno;
import java.sql.*; //Date;
import java.time.*; // LocalDate;
import java.util.*; //ArrayList;
//import java.util.List;
import javax.swing.*; //JOptionPane;
/**
 *
 * @author Usuario
 */
public class formAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form formAlumno
     */
    public formAlumno() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana
    AlumnoData alumno = new AlumnoData();
        desactivarCampos();
        jBGuardar.setEnabled(false);
        jBEliminar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAlumno = new javax.swing.JLabel();
        jLDocumento = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jLFechaNacimiento = new javax.swing.JLabel();
        jRBEstado = new javax.swing.JRadioButton();
        jTDocumento = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jDateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.activeCaption);
        setBorder(null);
        setTitle("Alumnos");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLAlumno.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLAlumno.setForeground(new java.awt.Color(0, 0, 0));
        jLAlumno.setText("Alumno");
        getContentPane().add(jLAlumno);
        jLAlumno.setBounds(354, 6, 82, 22);

        jLDocumento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLDocumento.setForeground(new java.awt.Color(0, 0, 0));
        jLDocumento.setText("Documento");
        getContentPane().add(jLDocumento);
        jLDocumento.setBounds(212, 110, 83, 17);

        jLApellido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLApellido.setForeground(new java.awt.Color(0, 0, 0));
        jLApellido.setText("Apellido");
        getContentPane().add(jLApellido);
        jLApellido.setBounds(212, 179, 83, 17);

        jLNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLNombre.setText("Nombre");
        getContentPane().add(jLNombre);
        jLNombre.setBounds(212, 241, 83, 17);

        jLEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(0, 0, 0));
        jLEstado.setText("Estado");
        getContentPane().add(jLEstado);
        jLEstado.setBounds(212, 292, 83, 17);

        jLFechaNacimiento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        jLFechaNacimiento.setText("Fecha de Nacimiento");
        getContentPane().add(jLFechaNacimiento);
        jLFechaNacimiento.setBounds(167, 353, 147, 17);
        getContentPane().add(jRBEstado);
        jRBEstado.setBounds(322, 281, 28, 28);

        jTDocumento.setBackground(java.awt.Color.white);
        getContentPane().add(jTDocumento);
        jTDocumento.setBounds(324, 106, 142, 24);

        jTApellido.setBackground(java.awt.Color.white);
        getContentPane().add(jTApellido);
        jTApellido.setBounds(324, 172, 142, 24);

        jTNombre.setBackground(java.awt.Color.white);
        getContentPane().add(jTNombre);
        jTNombre.setBounds(324, 234, 142, 24);

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbBuscar);
        jbBuscar.setBounds(506, 102, 80, 32);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir);
        jBSalir.setBounds(567, 516, 70, 32);

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEliminar);
        jBEliminar.setBounds(459, 516, 90, 32);

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGuardar);
        jBGuardar.setBounds(329, 516, 90, 32);

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBNuevo);
        jBNuevo.setBounds(231, 516, 80, 32);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(167, 40, 456, 10);
        getContentPane().add(jDateFechaNacimiento);
        jDateFechaNacimiento.setBounds(400, 350, 260, 29);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
 //ANDA BIEN TERMINADO falta mostrar la fecha
        try {
            Alumno a = new Alumno();
            a = null;
            int dni = Integer.parseInt(jTDocumento.getText());
            AlumnoData listAlumno = new AlumnoData();
            a = listAlumno.buscarAlumnoPorDni(dni);
            abilitarCampos();
            jTApellido.setText(a.getApellido());
            jTNombre.setText(a.getNombre());
            jBEliminar.setEnabled(true);
            //jDateFechaNacimiento.setDate(a.getFechaDeNacimiento());
            jDateFechaNacimiento.setDate(java.sql.Date.valueOf(a.getFechaDeNacimiento()));

// jDFechaNacimiento.setDate(Date.valueOf(a.getFechaDeNacimiento())).toLocalDate;
            if (a.equals(null)) {
                JOptionPane.showMessageDialog(null, "El alumno no existe ");
                jTDocumento.requestFocus();
               // jTDocumento.setText("");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el número de documento");
            jTDocumento.requestFocus();
            limpiarCampos();
        }
            jTDocumento.requestFocus();
           // jTDocumento.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed

//FUNCIONA TERMINADO
        abilitarCampos();
        limpiarCampos();
        jTDocumento.requestFocus();
        jTDocumento.setText("");

        jBGuardar.setEnabled(true);
        jRBEstado.setEnabled(false);
        jBEliminar.setEnabled(false);
        jBNuevo.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
 //FUNCIONA  TERMINADO
        Alumno alumno = new Alumno();
        AlumnoData alumnoData = new AlumnoData();

        alumno.setDni(Integer.parseInt(jTDocumento.getText()));  //int dni, String apellido, String nombre, LocalDate fechaDeNaciemiento, boolean estado
        alumno.setApellido(jTApellido.getText());
        alumno.setNombre(jTNombre.getText());
        alumno.setEstado(true);
        LocalDate fecNac = jDateFechaNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();// como declarar estas variables
        alumno.setFechaDeNacimiento(fecNac);
        alumnoData.guardarAlumno(alumno);
        JOptionPane.showMessageDialog(null, "Alumno " + alumno.getApellido() + " guardado con exito. ");
        limpiarCampos();
        jTDocumento.requestFocus();
        desactivarCampos();
        jBNuevo.setEnabled(true);

     

        // TODO add your handling code here:
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
 //ESTE funciona FALTA pulir
        
        
          
            int dni = Integer.parseInt(jTDocumento.getText());
            AlumnoData listAlumno = new AlumnoData();
            listAlumno.eliminarAlumno(dni);
            abilitarCampos();
            

        JOptionPane.showMessageDialog(null, "El alumno  a sido dado de baja ");
       // limpiarCampos();
        desactivarCampos();
           jTDocumento.requestFocus();
           jTDocumento.setText("");
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private com.toedter.calendar.JDateChooser jDateFechaNacimiento;
    private javax.swing.JLabel jLAlumno;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLDocumento;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFechaNacimiento;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBEstado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTDocumento;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JButton jbBuscar;
    // End of variables declaration//GEN-END:variables
    public void desactivarCampos() {

        jTApellido.setEnabled(false);
        jTNombre.setEnabled(false);

    }

    public void abilitarCampos() {
        jTDocumento.setEnabled(true);
        jTNombre.setEnabled(true);
        jTApellido.setEnabled(true);
    }

    public void limpiarCampos() {
        jTDocumento.setText("");
        jTNombre.setText("");
        jTApellido.setText("");

    }


}
