package vistas;

import AccesoADatos.AlumnoData;
import AccesoADatos.InscripcionData;
import AccesoADatos.MateriaData;
import Entidades.Alumno;
import Entidades.Inscripcion;
import Entidades.Materia;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class Manipulacion_De_Notas extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private AlumnoData a1 = new AlumnoData();
    private Alumno a = new Alumno();
    private Inscripcion ins = new Inscripcion();
    private InscripcionData ins_data = new InscripcionData();

    /**
     * Creates new form Manipulacion_De_Notas
     */
    public Manipulacion_De_Notas() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana
        this.setTitle("Carga de Notas");

        cargarCombo();
        agregarTabla();
        
        //carga datos del primer alumno del combo
        List<Materia> materiasCursadas = ins_data.obtenerMateriaCursada(ComboBox1.getItemAt(ComboBox1.getSelectedIndex()).getIdAlumno());
        modeloTabla.setRowCount(0);
        for (Materia mat : materiasCursadas) {
                // Agrega una fila con los datos de la materia
                modeloTabla.addRow(new Object[]{mat.getIdMateria(), mat.getNombre(), ins_data.obtenerNota(ComboBox1.getItemAt(ComboBox1.getSelectedIndex()).getIdAlumno(),mat.getIdMateria())});
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        ComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        BotonGuardar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Listado de Alumnos por Materias");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setBackground(java.awt.SystemColor.activeCaption);
        setBorder(null);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccione un Alumno");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 70, 156, 19);

        ComboBox1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox1);
        ComboBox1.setBounds(380, 70, 213, 25);

        tabla1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tabla1ComponentAdded(evt);
            }
        });
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 140, 401, 227);

        BotonGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonGuardar);
        BotonGuardar.setBounds(220, 390, 82, 31);

        BotonSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir);
        BotonSalir.setBounds(460, 390, 80, 31);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Listado de Alumnos por Materias");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 10, 287, 22);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(200, 40, 390, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // Boton Salir
        dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed
        
        Inscripcion in = new Inscripcion();
        MateriaData matData = new MateriaData();
        
        // Llamar al método obtenerMateriasCursadas para obtener la lista de materias cursadas para el alumno
        List<Materia> materiasCursadas = ins_data.obtenerMateriaCursada(ComboBox1.getItemAt(ComboBox1.getSelectedIndex()).getIdAlumno());
        if (materiasCursadas != null) {
            modeloTabla.setRowCount(0);
            // Agregar las materias cursadas a la tabla
            for (Materia mat : materiasCursadas) {
                // Agrega una fila con los datos de la materia
                modeloTabla.addRow(new Object[]{mat.getIdMateria(), mat.getNombre(), ins_data.obtenerNota(ComboBox1.getItemAt(ComboBox1.getSelectedIndex()).getIdAlumno(),mat.getIdMateria())});
            }
        }
    }//GEN-LAST:event_ComboBox1ActionPerformed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked

    }//GEN-LAST:event_tabla1MouseClicked

    private void tabla1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tabla1ComponentAdded
    }//GEN-LAST:event_tabla1ComponentAdded

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            int idMat = Integer.valueOf(modeloTabla.getValueAt(i, 0).toString());
            int idAlu = ComboBox1.getItemAt(ComboBox1.getSelectedIndex()).getIdAlumno();
            double nota = Double.parseDouble(modeloTabla.getValueAt(i, 2).toString());
            ins_data.actualizarNota(idAlu, idMat, nota);
        }
        JOptionPane.showMessageDialog(null, "Nota Actualizada");
    }//GEN-LAST:event_BotonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JComboBox<Alumno> ComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
    private void cargarCombo() {
        List<Alumno> listaAlumnos = a1.listarAlumnos();
        for (Alumno alumno : listaAlumnos) {
            ComboBox1.addItem(new Alumno(alumno.getIdAlumno(),alumno.getDni(),alumno.getApellido(),alumno.getNombre()));
        }
    }

    private void agregarTabla() {
        tabla1.setModel(modeloTabla);
        modeloTabla.addColumn("Codigo");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Nota");
    }
}
